version: '3'
services:
  db:
    restart: always
    ports:
      - "5432:5432"
    build:
      context: ./postgres
      dockerfile: Dockerfile
  app:
    env_file: .env 
    build: .
    ports:
      - '80:1128'
    depends_on:
      - db